from pathlib import Path
from typing import List, Tuple

import pandas as pd


FALLBACK_LIQUID_TICKERS = [
    "AAPL",
    "MSFT",
    "NVDA",
    "AMZN",
    "META",
    "GOOGL",
    "GOOG",
    "AVGO",
    "TSLA",
    "BRK.B",
    "JPM",
    "LLY",
    "V",
    "UNH",
    "XOM",
    "MA",
    "COST",
    "HD",
    "PG",
    "NFLX",
    "WMT",
    "BAC",
    "ABBV",
    "CRM",
    "AMD",
    "KO",
    "PEP",
    "MRK",
    "ORCL",
    "CVX",
    "WFC",
    "CSCO",
    "MCD",
    "DIS",
    "ABT",
    "INTU",
    "QCOM",
    "IBM",
    "GE",
    "CAT",
    "NOW",
    "TXN",
    "AMAT",
    "UBER",
    "SPY",
    "QQQ",
]

SP100_TICKERS = [
    "AAPL",
    "ABBV",
    "ABT",
    "ACN",
    "ADBE",
    "AIG",
    "AMD",
    "AMGN",
    "AMT",
    "AMZN",
    "AVGO",
    "AXP",
    "BA",
    "BAC",
    "BK",
    "BKNG",
    "BLK",
    "BMY",
    "BRK.B",
    "C",
    "CAT",
    "CHTR",
    "CL",
    "CMCSA",
    "COF",
    "COP",
    "COST",
    "CRM",
    "CSCO",
    "CVS",
    "CVX",
    "DE",
    "DHR",
    "DIS",
    "DOW",
    "DUK",
    "EMR",
    "EXC",
    "F",
    "FDX",
    "GD",
    "GE",
    "GILD",
    "GM",
    "GOOG",
    "GOOGL",
    "GS",
    "HD",
    "HON",
    "IBM",
    "INTC",
    "INTU",
    "JNJ",
    "JPM",
    "KHC",
    "KO",
    "LIN",
    "LLY",
    "LMT",
    "LOW",
    "MA",
    "MCD",
    "MDLZ",
    "MDT",
    "MET",
    "META",
    "MMM",
    "MO",
    "MRK",
    "MS",
    "MSFT",
    "NEE",
    "NFLX",
    "NKE",
    "NVDA",
    "ORCL",
    "PEP",
    "PFE",
    "PG",
    "PM",
    "PYPL",
    "QCOM",
    "RTX",
    "SBUX",
    "SCHW",
    "SO",
    "SPG",
    "T",
    "TGT",
    "TMO",
    "TMUS",
    "TSLA",
    "TXN",
    "UNH",
    "UNP",
    "UPS",
    "USB",
    "V",
    "VZ",
    "WBA",
    "WFC",
    "WMT",
    "XOM",
]


def load_sp500_tickers() -> Tuple[List[str], str]:
    data_path = Path("data/sp500_tickers.csv")
    if data_path.exists():
        frame = pd.read_csv(data_path)
        if "symbol" in frame.columns and not frame.empty:
            return frame["symbol"].dropna().astype(str).str.upper().tolist(), ""

    try:
        tables = pd.read_html("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")
        frame = tables[0]
        tickers = frame["Symbol"].astype(str).str.replace(".", "/", regex=False).str.upper().tolist()
        data_path.parent.mkdir(parents=True, exist_ok=True)
        pd.DataFrame({"symbol": tickers}).to_csv(data_path, index=False)
        return tickers, ""
    except Exception:
        return FALLBACK_LIQUID_TICKERS, "Could not load the live S&P 500 list, so the dashboard is using a liquid starter universe."


def load_sp100_tickers() -> Tuple[List[str], str]:
    return SP100_TICKERS, ""
